Clean up After Test DBs
zemirco/couchdb pull request #10
Opened 2017-03-15 04:36 UTC by ryanjyoder

Cleans up test dbs created during tests.
Moves current "deletes" to defer after creation, which prevents orphan dbs from being left behind when a test errors out.

2017-03-15 05:48 UTC, zemirco requested changes
Your pull requests are really good! Just one minor issue with duplicate `client.Delete`.

2017-03-15 05:48 UTC, zemirco commented on client_test.go
> +	defer client.Delete(name)
The `client.Delete` at the end of the method can then be deleted, right?

2017-03-15 12:48 UTC, ryanjyoder commented on client_test.go
> +	defer client.Delete(name)
I deleted the **Delete** at the end of this method. Are you talking about this line?
https://github.com/zemirco/couchdb/pull/10/files#diff-51565ad50d7426213c2f33579f6f0e71L567
It looks like I missed one. I'll updated it.

2017-03-15 15:22 UTC, zemirco commented on client_test.go
> +	defer client.Delete(name)
Yeah I was talking about the one you missed. I just could not create the comment at that line since you didn't touch it in your pull requests. GitHub just doesn't allow adding comments to lines which were not modified

2017-03-16 05:04 UTC, zemirco approved these changes

2017-03-16 05:05 UTC, merged