Handle slashes in names
zemirco/couchdb pull request #9
Opened 2017-03-12 20:39 UTC by ryanjyoder

Slashes in DB names should be escaped. The same is true for document ids.

_I used PathEscape (in net/url) which is only available in go 1.8._

Also note, there is a known bug with couchdb not handling literal '+' in database names (and document ids). I'm not testing for this as it fails on couchdb's end.

2017-03-13 15:45 UTC, zemirco commented
Thank you! Will take a look within the next days.

2017-03-13 18:32 UTC, zemirco requested changes
Just some minor things. Looks great overall!

2017-03-13 18:32 UTC, zemirco commented on client_test.go
> +	validSpecialCharacter = "/_$()-/"
Do we need the trailing slash `/`? Isn't this character already tested with the first slash?

And is that documented somewhere which characters are allowed?

2017-03-13 18:32 UTC, zemirco commented on client_test.go
> +	// The folllowing characters are valid in databse names: /_$()-+
Typo in `databse`.

2017-03-13 18:32 UTC, zemirco commented on client_test.go
> +	// The folllowing characters are valid in databse names: /_$()-+
Typo in `folllowing`.

2017-03-13 19:08 UTC, ryanjyoder commented on client_test.go
> +	validSpecialCharacter = "/_$()-/"
Yeah we can remove the second slash.
http://docs.couchdb.org/en/1.6.0/api/database/common.html

> The database name {db} must be composed by following next rules:
>     Name must begin with a lowercase letter (a-z)
>     Lowercase characters (a-z)
>     Digits (0-9)
>     Any of the characters _, $, (, ), +, -, and /.
> 
> If you’re familiar with Regular Expressions, the rules above could be written as ^[a-z][a-z0-9_$()+/-]*$.

2017-03-13 19:21 UTC, ryanjyoder commented on client_test.go
> +	validSpecialCharacter = "/_$()-/"
For document id, I haven't been able to find any restrictions however...

2017-03-15 04:48 UTC, zemirco approved these changes

2017-03-15 04:48 UTC, merged